[phases.setup]
nixPkgs = ['php82', 'php82Extensions.gd', 'php82Extensions.opcache', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.redis', 'php82Extensions.sodium', 'php82Extensions.intl']